# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Null_Bit.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 773)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1071, 771))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 128))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Mode_Selection = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.Mode_Selection.setMinimumSize(QtCore.QSize(100, 0))
        self.Mode_Selection.setObjectName("Mode_Selection")
        self.Mode_Selection.addItem("")
        self.Mode_Selection.addItem("")
        self.horizontalLayout.addWidget(self.Mode_Selection)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.Type_Selection = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.Type_Selection.setMinimumSize(QtCore.QSize(225, 0))
        self.Type_Selection.setObjectName("Type_Selection")
        self.Type_Selection.addItem("")
        self.Type_Selection.addItem("")
        self.Type_Selection.addItem("")
        self.Type_Selection.addItem("")
        self.horizontalLayout.addWidget(self.Type_Selection)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Title1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Title1.setObjectName("Title1")
        self.verticalLayout.addWidget(self.Title1)
        self.Input_Box = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.Input_Box.setObjectName("Input_Box")
        self.verticalLayout.addWidget(self.Input_Box)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Title2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Title2.setObjectName("Title2")
        self.verticalLayout_2.addWidget(self.Title2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Key_Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Key_Label.setObjectName("Key_Label")
        self.verticalLayout_3.addWidget(self.Key_Label)
        self.Key_Box = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Key_Box.sizePolicy().hasHeightForWidth())
        self.Key_Box.setSizePolicy(sizePolicy)
        self.Key_Box.setObjectName("Key_Box")
        self.verticalLayout_3.addWidget(self.Key_Box)
        self.Load_Key_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Load_Key_Button.setObjectName("Load_Key_Button")
        self.verticalLayout_3.addWidget(self.Load_Key_Button)
        self.Save_Key_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Save_Key_Button.setObjectName("Save_Key_Button")
        self.verticalLayout_3.addWidget(self.Save_Key_Button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Null Bit"))
        self.label.setText(_translate("MainWindow", "Null Bit Encryption/Decryption"))
        self.label_2.setText(_translate("MainWindow", "Mode:"))
        self.Mode_Selection.setItemText(0, _translate("MainWindow", "Encrypt"))
        self.Mode_Selection.setItemText(1, _translate("MainWindow", "Decrypt"))
        self.label_3.setText(_translate("MainWindow", "Encryption Type"))
        self.Type_Selection.setItemText(0, _translate("MainWindow", "XOR Cipher"))
        self.Type_Selection.setItemText(1, _translate("MainWindow", "Columnar Transposition Cipher"))
        self.Type_Selection.setItemText(2, _translate("MainWindow", "Vigenere Cipher"))
        self.Type_Selection.setItemText(3, _translate("MainWindow", "Pig Latin"))
        self.Title1.setText(_translate("MainWindow", "TextLabel"))
        self.Title2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_3.setText(_translate("MainWindow", "Save Encrypted Output To File"))
        self.Key_Label.setText(_translate("MainWindow", "TextLabel"))
        self.Load_Key_Button.setText(_translate("MainWindow", "Load Key From File"))
        self.Save_Key_Button.setText(_translate("MainWindow", "Save Key To File"))
        self.pushButton_4.setText(_translate("MainWindow", "Run"))
        self.pushButton_5.setText(_translate("MainWindow", "Clear"))
